#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"

usage() {
  cat <<'EOF'
Usage: run_codex_exec.sh --prompt FILE --report PATH [options]

Run a checked-in prompt through codex exec with:
- auth preflight
- lock-based serialization
- persisted final message
- JSONL event logging

Options:
  --prompt FILE         Checked-in prompt file to execute.
  --report PATH         Final markdown output path.
  --context-file FILE   Optional markdown or text file appended as runtime context.
  --log-dir DIR         Directory for prompt snapshots and exec logs.
  --label NAME          Label prefix for generated log files.
  --lock-name NAME      Lock name for with_codex_lock.sh. Default: codex-chatgpt-auth
  --lock-timeout SEC    Lock wait timeout. Default: 1800
  --exec-timeout SEC    Hard timeout for codex exec. Default: 900
  -h, --help            Show this help message.
EOF
}

ROOT_DIR="$(agentslam_root)"
PROMPT_PATH=""
REPORT_PATH=""
CONTEXT_FILE=""
LABEL=""
LOCK_NAME="codex-chatgpt-auth"
LOCK_TIMEOUT=1800
EXEC_TIMEOUT=900
STAMP="$(ops_timestamp)"
LOG_DIR="${ROOT_DIR}/artifacts/ops/codex/${STAMP}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prompt)
      PROMPT_PATH="$2"
      shift 2
      ;;
    --report)
      REPORT_PATH="$2"
      shift 2
      ;;
    --context-file)
      CONTEXT_FILE="$2"
      shift 2
      ;;
    --log-dir)
      LOG_DIR="$2"
      shift 2
      ;;
    --label)
      LABEL="$2"
      shift 2
      ;;
    --lock-name)
      LOCK_NAME="$2"
      shift 2
      ;;
    --lock-timeout)
      LOCK_TIMEOUT="$2"
      shift 2
      ;;
    --exec-timeout)
      EXEC_TIMEOUT="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "${PROMPT_PATH}" || -z "${REPORT_PATH}" ]]; then
  echo "--prompt and --report are required." >&2
  usage >&2
  exit 2
fi

if [[ ! -f "${PROMPT_PATH}" ]]; then
  echo "Prompt file not found: ${PROMPT_PATH}" >&2
  exit 1
fi

if [[ -n "${CONTEXT_FILE}" && ! -f "${CONTEXT_FILE}" ]]; then
  echo "Context file not found: ${CONTEXT_FILE}" >&2
  exit 1
fi

if [[ -z "${LABEL}" ]]; then
  LABEL="$(basename "${PROMPT_PATH}" .md)"
fi

mkdir -p "${LOG_DIR}" "$(dirname "${REPORT_PATH}")"

AUTH_REPORT="${LOG_DIR}/${LABEL}_auth_check.md"
bash "${ROOT_DIR}/scripts/ops/check_codex_auth.sh" --report-path "${AUTH_REPORT}" --quiet

MERGED_PROMPT="${LOG_DIR}/${LABEL}_prompt.md"
EVENT_LOG="${LOG_DIR}/${LABEL}_events.jsonl"
STDERR_LOG="${LOG_DIR}/${LABEL}_stderr.log"
META_PATH="${LOG_DIR}/${LABEL}_meta.txt"

EXEC_CMD=(
  codex exec
  -C "${ROOT_DIR}"
  --color never
  --json
  -o "${REPORT_PATH}"
  -c 'approval_policy="never"'
  -c 'sandbox_mode="workspace-write"'
  -
)

if command -v timeout >/dev/null 2>&1; then
  EXEC_CMD=(timeout --foreground "${EXEC_TIMEOUT}" "${EXEC_CMD[@]}")
fi

cat "${PROMPT_PATH}" >"${MERGED_PROMPT}"
cat >>"${MERGED_PROMPT}" <<EOF

## Runtime Context

- repository root: \`${ROOT_DIR}\`
- final report path: \`${REPORT_PATH}\`
- prompt path: \`${PROMPT_PATH}\`
- log directory: \`${LOG_DIR}\`
- current timestamp: ${STAMP}

Write your final response as markdown suitable to save directly at the report path above.
EOF

if [[ -n "${CONTEXT_FILE}" ]]; then
  cat >>"${MERGED_PROMPT}" <<EOF

## Appended Runtime Notes

The file below was generated by the runner wrapper. Read it after the checked-in prompt and obey any concrete paths it provides.

EOF
  cat "${CONTEXT_FILE}" >>"${MERGED_PROMPT}"
fi

set +e
bash "${ROOT_DIR}/scripts/ops/with_codex_lock.sh" \
  --lock-name "${LOCK_NAME}" \
  --timeout "${LOCK_TIMEOUT}" \
  -- \
  "${EXEC_CMD[@]}" \
  <"${MERGED_PROMPT}" >"${EVENT_LOG}" 2>"${STDERR_LOG}"
STATUS=$?
set -e

cat >"${META_PATH}" <<EOF
label=${LABEL}
status=${STATUS}
prompt_path=${PROMPT_PATH}
merged_prompt=${MERGED_PROMPT}
report_path=${REPORT_PATH}
event_log=${EVENT_LOG}
stderr_log=${STDERR_LOG}
auth_report=${AUTH_REPORT}
timestamp=${STAMP}
exec_timeout=${EXEC_TIMEOUT}
EOF

if [[ ${STATUS} -eq 0 && -s "${REPORT_PATH}" ]]; then
  cat <<EOF
codex exec completed
- report: ${REPORT_PATH}
- event_log: ${EVENT_LOG}
- stderr_log: ${STDERR_LOG}
- meta: ${META_PATH}
EOF
  exit 0
fi

echo "codex exec failed; inspect ${STDERR_LOG} and ${EVENT_LOG}" >&2
exit "${STATUS}"
